[package]
name = "audio-graph-settings"
version.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"

[dependencies]
plugin-host.workspace = true
log.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
serde_json.workspace = true
