//! The wrapper's host-visible parameters.
//!
//! The sub-plugin's parameters are not published directly to the DAW. Instead,
//! the host sees a fixed bank of generic slots that the user binds to sub-plugin
//! parameters inside the wrapper. This decoupling allows sub-plugins to be swapped
//! without breaking host automation lanes.

use std::sync::Arc;

use crate::config::SLOT_COUNT;
use nice_plug::params::persist::PersistentField;
use nice_plug::prelude::*;

/// Serialised wrapper state, carried through nice-plug's `#[persist]` support.
///
/// A string rather than a struct because the payload includes the sub-plugin's
/// opaque chunk, and nice-plug persists fields as JSON strings.
#[derive(Default)]
pub struct PersistedState(pub std::sync::RwLock<String>);

impl<'a> PersistentField<'a, String> for PersistedState {
    fn set(&self, new_value: String) {
        *self.0.write().unwrap() = new_value;
    }

    fn map<F, R>(&self, f: F) -> R
    where
        F: Fn(&String) -> R,
    {
        f(&self.0.read().unwrap())
    }
}

#[derive(Params)]
pub struct WrapperParams {
    /// Everything the wrapper owns that is not a slot value: the slot table,
    /// the bindings, which sub-plugin is loaded, and its state chunk.
    ///
    /// Kept as one persisted blob rather than many fields so its layout can
    /// evolve without inventing a new parameter each time.
    #[persist = "wrapper-state"]
    pub state: PersistedState,

    /// The slot values themselves.
    ///
    /// Their IDs are the stable strings `slot_1`..`slot_32` (generated by array
    /// nesting). nice-plug derives VST3 ParamIDs deterministically by hashing
    /// the string ID, ensuring DAW automation survives sub-plugin swaps.
    ///
    /// Groups are omitted so the host displays a flat list (`Audio Graph FX > Slot 1`)
    /// rather than creating nested sub-groups.
    #[nested(array)]
    pub slots: [SlotParam; SLOT_COUNT],
}

#[derive(Params)]
pub struct SlotParam {
    #[id = "slot"]
    pub value: FloatParam,
}

impl SlotParam {
    /// `index` is zero-based; the name is not.
    ///
    /// nice-plug numbers array elements from 1 in the parameter id, so a
    /// zero-based display name would disagree with the DAW about which slot is
    /// which — and the id is the thing automation is attached to.
    fn new(index: usize) -> SlotParam {
        SlotParam {
            // Plain 0..1: the slot itself has no units. The mapping onto the
            // bound parameter's real range happens in the adapter, where the
            // range is actually known.
            value: FloatParam::new(
                format!("Slot {}", index + 1),
                0.0,
                FloatRange::Linear { min: 0.0, max: 1.0 },
            ),
        }
    }
}

impl Default for SlotParam {
    fn default() -> Self {
        SlotParam::new(0)
    }
}

impl Default for WrapperParams {
    fn default() -> Self {
        WrapperParams {
            state: PersistedState::default(),
            slots: std::array::from_fn(SlotParam::new),
        }
    }
}

impl WrapperParams {
    pub fn new() -> Arc<WrapperParams> {
        Arc::new(WrapperParams::default())
    }

    /// Current slot values, in the order the adapter expects.
    pub fn slot_values(&self, out: &mut Vec<f64>) {
        out.clear();
        out.extend(self.slots.iter().map(|s| s.value.value() as f64));
    }
}
