[package]
name = "clap-host"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
plugin-host-api.workspace = true
host-window.workspace = true
clap-sys.workspace = true
log.workspace = true

[target."cfg(windows)".dependencies]
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_System_LibraryLoader"] }

[target."cfg(unix)".dependencies]
libc = "0.2"

[dev-dependencies]
plugin-host-api.workspace = true
