[package]
name = "wrapper-plugin"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
plugin-host-api.workspace = true
subhost-adapter.workspace = true
vst3-host.workspace = true
nice-plug = "0.3"
nice-log = "0.3"
log.workspace = true
serde.workspace = true
serde_json.workspace = true
